name: rebotai
description: 'A GitHub bot powered by OpenAI for code review on pull requests.'
branding:
  icon: 'code'
  color: 'white'

inputs:
  gh-token:
    description: 'GitHub token for accessing repository'
    required: true
  openai-api-key:
    description: 'OpenAI API key for accessing OpenAI services'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.gh-token }}
    - ${{ inputs.openai-api-key }}
